// frontend/src/features/workspace/components/CommandPalette.tsx
import { useEffect, useMemo, useRef, useState } from 'react';

import { CheckIcon, ChevronRightIcon, PlusIcon, SearchIcon } from '@/components/icons';
import type { WorkspaceModel } from '@/features/workspace/hooks/use-workspace';
import { getSuggestions, parseInput, type Suggestion } from '@/features/workspace/utils/smart-input';
import type { Project } from '@/types/api';

interface CommandPaletteProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  workspace: WorkspaceModel;
}

interface Result {
  type: 'project' | 'task' | 'create';
  id: string;
  title: string;
  projectId?: string;
  projectName?: string;
  isDone?: boolean;
}

export function CommandPalette({ open, onOpenChange, workspace }: CommandPaletteProps) {
  const searchInputRef = useRef<HTMLInputElement>(null);
  const taskInputRef = useRef<HTMLInputElement>(null);
  const projectInputRef = useRef<HTMLInputElement>(null);
  const [query, setQuery] = useState('');
  const [selectedIndex, setSelectedIndex] = useState(0);
  const [atSuggestions, setAtSuggestions] = useState<Suggestion[]>([]);
  const [atSelectedIndex, setAtSelectedIndex] = useState(0);
  const [showAtSuggestions, setShowAtSuggestions] = useState(false);
  const [atSource, setAtSource] = useState<'search' | 'create'>('search');
  const [creatingTask, setCreatingTask] = useState('');
  const [projectQuery, setProjectQuery] = useState('');
  const [projectIndex, setProjectIndex] = useState(0);
  const [selectedProjectId, setSelectedProjectId] = useState<string | null>(null);
  const [projectPickerOpen, setProjectPickerOpen] = useState(false);

  const results = useMemo(
    () => buildResults(query, workspace.projects, workspace.tasks),
    [query, workspace.projects, workspace.tasks],
  );
  const projectResults = results.filter((result) => result.type === 'project');
  const taskResults = results.filter((result) => result.type === 'task');
  const leafProjects = useMemo(() => {
    const parents = new Set(workspace.projects.filter((project) => project.parent_id).map((project) => project.parent_id));
    return workspace.projects
      .filter((project) => !parents.has(project.id))
      .filter((project) => !projectQuery.trim() || matches(project.title, projectQuery));
  }, [projectQuery, workspace.projects]);
  const visibleProjects = projectQuery.trim() ? leafProjects.slice(0, 12) : leafProjects.slice(0, 7);
  const selectedProject = selectedProjectId
    ? workspace.projects.find((project) => project.id === selectedProjectId)
    : undefined;

  useEffect(() => {
    window.setTimeout(() => searchInputRef.current?.focus(), 50);
  }, []);

  useEffect(() => {
    if (!open) return;
    const previous = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    return () => {
      document.body.style.overflow = previous;
    };
  }, [open]);

  useEffect(() => {
    const closeWhenFocusFallsOutside = (event: KeyboardEvent) => {
      if (event.key === 'Escape' && !event.defaultPrevented) onOpenChange(false);
    };
    window.addEventListener('keydown', closeWhenFocusFallsOutside);
    return () => window.removeEventListener('keydown', closeWhenFocusFallsOutside);
  }, [onOpenChange]);

  const updateAtSuggestions = (text: string, source: 'search' | 'create') => {
    const lastWord = text.split(/\s/).at(-1) ?? '';
    if (!lastWord.startsWith('@') || lastWord.length <= 1) {
      setShowAtSuggestions(false);
      return;
    }
    const suggestions = getSuggestions(lastWord.slice(1), []);
    setAtSource(source);
    setAtSuggestions(suggestions);
    setAtSelectedIndex(0);
    setShowAtSuggestions(suggestions.length > 0);
  };

  const applyAtSuggestion = (suggestion: Suggestion) => {
    const sourceText = atSource === 'create' ? creatingTask : query;
    const words = sourceText.split(/\s/);
    words[words.length - 1] = `@${suggestion.value}`;
    const nextValue = `${words.join(' ')} `;
    if (atSource === 'create') setCreatingTask(nextValue);
    else setQuery(nextValue);
    setShowAtSuggestions(false);
    window.setTimeout(() => (atSource === 'create' ? taskInputRef : searchInputRef).current?.focus(), 0);
  };

  const focusProjectInput = () => {
    setProjectPickerOpen(true);
    requestAnimationFrame(() => projectInputRef.current?.focus());
    window.setTimeout(() => projectInputRef.current?.focus(), 20);
  };

  const startCreate = () => {
    if (!query.trim()) return;
    setCreatingTask(query.trim());
    setProjectQuery('');
    setSelectedProjectId(null);
    setProjectPickerOpen(true);
    setProjectIndex(0);
    window.setTimeout(() => projectInputRef.current?.focus(), 0);
  };

  const selectProject = (projectId: string) => {
    setSelectedProjectId(projectId);
    setProjectQuery('');
    setProjectPickerOpen(false);
    setProjectIndex(Math.max(leafProjects.findIndex((project) => project.id === projectId), 0));
    requestAnimationFrame(() => taskInputRef.current?.focus());
    window.setTimeout(() => taskInputRef.current?.focus(), 20);
  };

  const submitCreatedTask = async () => {
    const title = creatingTask.trim();
    if (!title) {
      taskInputRef.current?.focus();
      return;
    }
    if (!selectedProjectId) {
      focusProjectInput();
      return;
    }
    const parsed = parseInput(creatingTask);
    const projectId = selectedProjectId;
    await workspace.createTask(projectId, { title: parsed.title || title, due_date: parsed.due_date });
    onOpenChange(false);
    window.setTimeout(() => document.getElementById(`project-${projectId}`)?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 200);
  };

  const activate = (result: Result) => {
    if (result.type === 'create') {
      startCreate();
      return;
    }
    onOpenChange(false);
    const projectId = result.type === 'project' ? result.id : result.projectId;
    window.setTimeout(() => document.getElementById(`project-${projectId}`)?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 150);
  };

  const onKeyDown = (event: React.KeyboardEvent) => {
    if (event.key === 'Escape') {
      event.preventDefault();
      if (showAtSuggestions) {
        setShowAtSuggestions(false);
      } else if (creatingTask && projectPickerOpen && selectedProjectId) {
        setProjectPickerOpen(false);
        setProjectQuery('');
        window.setTimeout(() => taskInputRef.current?.focus(), 0);
      } else if (creatingTask) {
        setCreatingTask('');
        window.setTimeout(() => searchInputRef.current?.focus(), 0);
      } else {
        onOpenChange(false);
      }
      return;
    }

    if (showAtSuggestions) {
      if (event.key === 'ArrowDown') {
        event.preventDefault();
        setAtSelectedIndex((index) => Math.min(index + 1, atSuggestions.length - 1));
        return;
      }
      if (event.key === 'ArrowUp') {
        event.preventDefault();
        setAtSelectedIndex((index) => Math.max(index - 1, 0));
        return;
      }
      if ((event.key === 'Tab' || event.key === 'Enter') && atSuggestions[atSelectedIndex]) {
        event.preventDefault();
        applyAtSuggestion(atSuggestions[atSelectedIndex]);
        return;
      }
    }

    if (creatingTask) {
      const isTaskInput = event.target === taskInputRef.current;
      const isProjectInput = event.target === projectInputRef.current;
      if (event.key === 'ArrowDown') {
        event.preventDefault();
        setProjectPickerOpen(true);
        setProjectIndex((index) => Math.min(index + 1, Math.max(visibleProjects.length - 1, 0)));
        if (!isProjectInput) projectInputRef.current?.focus();
        return;
      }
      if (event.key === 'ArrowUp') {
        event.preventDefault();
        setProjectPickerOpen(true);
        setProjectIndex((index) => Math.max(index - 1, 0));
        if (!isProjectInput) projectInputRef.current?.focus();
        return;
      }
      if (projectPickerOpen && (event.key === 'Tab' || event.key === 'Enter') && visibleProjects[projectIndex]) {
        event.preventDefault();
        selectProject(visibleProjects[projectIndex].id);
        return;
      }
      if (isTaskInput && event.key === 'Enter') {
        event.preventDefault();
        if (selectedProjectId) void submitCreatedTask();
        else focusProjectInput();
        return;
      }
      if (isTaskInput && event.key === 'Tab' && !event.shiftKey && !selectedProjectId) {
        event.preventDefault();
        focusProjectInput();
      }
      return;
    }

    if (event.key === 'ArrowDown') {
      event.preventDefault();
      setSelectedIndex((index) => Math.min(index + 1, Math.max(results.length - 1, 0)));
    } else if (event.key === 'ArrowUp') {
      event.preventDefault();
      setSelectedIndex((index) => Math.max(index - 1, 0));
    } else if (event.key === 'Enter' || event.key === 'Tab') {
      event.preventDefault();
      if (results[selectedIndex]) activate(results[selectedIndex]);
      else if (query.trim()) startCreate();
    }
  };

  if (!open) return null;
  const parsedPreview = parseInput(creatingTask);
  const createFirst = results[0]?.type === 'create';

  return (
    <div className="fixed inset-0 z-[90] flex items-start justify-center px-4 pt-[12vh] md:pt-[15vh]" onKeyDown={onKeyDown}>
      <button aria-label="close command palette" className="fade-in absolute inset-0 bg-black/55 backdrop-blur-[4px]" onClick={() => onOpenChange(false)} type="button" />
      <section aria-label="command palette" aria-modal="true" className="modal-in relative w-full max-w-xl overflow-hidden rounded-2xl border border-border bg-elevated/95 shadow-[0_28px_100px_rgba(0,0,0,0.38)] backdrop-blur-2xl" role="dialog">
        {creatingTask ? (
          <>
            <div className="border-b border-border/70 px-4 pb-3 pt-4">
              <div className="flex items-center gap-2">
                <input
                  ref={taskInputRef}
                  aria-label="new task"
                  className="min-w-0 flex-1 bg-transparent text-[15px] leading-6 text-text outline-none placeholder:text-text-muted/60"
                  onChange={(event) => {
                    setCreatingTask(event.target.value);
                    updateAtSuggestions(event.target.value, 'create');
                  }}
                  placeholder="new task..."
                  value={creatingTask}
                />
                {parsedPreview.due_date ? <DateChip value={parsedPreview.due_date} /> : null}
              </div>
              {showAtSuggestions && atSource === 'create' ? <SuggestionList items={atSuggestions} selectedIndex={atSelectedIndex} onSelect={applyAtSuggestion} /> : null}
              <div className="mt-3 flex items-center gap-2">
                <button className="inline-flex min-w-0 items-center gap-1.5 rounded-md border border-border bg-surface/70 px-2 py-1 text-xs text-text-secondary hover:bg-surface hover:text-text" onClick={focusProjectInput} type="button">
                  <span className="h-1.5 w-1.5 shrink-0 rounded-full" style={{ background: selectedProject?.color ?? '#777d72' }} />
                  <span className="max-w-[220px] truncate">{selectedProject?.title ?? 'project'}</span>
                </button>
              </div>
            </div>

            {projectPickerOpen || !selectedProjectId ? (
              <div className="border-b border-border/70">
                <div className="px-4 py-2">
                  <input
                    ref={projectInputRef}
                    aria-label="project"
                    className="w-full bg-transparent text-sm text-text outline-none placeholder:text-text-muted/60"
                    onChange={(event) => {
                      setProjectQuery(event.target.value);
                      setProjectIndex(0);
                      setProjectPickerOpen(true);
                    }}
                    placeholder={selectedProject ? 'change project...' : 'project...'}
                    value={projectQuery}
                  />
                </div>
                <div className="scrollbar-thin max-h-[34vh] overflow-y-auto pb-1">
                  {visibleProjects.map((project, index) => (
                    <button className="block w-full px-3 py-0.5 text-left" key={project.id} onClick={() => selectProject(project.id)} type="button">
                      <span className={`flex items-center gap-2.5 rounded-md px-2 py-2 text-sm ${index === projectIndex ? 'bg-surface text-text' : selectedProjectId === project.id ? 'bg-surface/60 text-text' : 'text-text-secondary hover:bg-surface/50'}`}>
                        <span className="h-1.5 w-1.5 shrink-0 rounded-full" style={{ background: project.color ?? '#525252' }} />
                        <span className="truncate">{project.title}</span>
                        <span className="ml-auto flex min-w-0 items-center gap-2">
                          {parentName(project, workspace.projects) ? <span className="max-w-[110px] truncate text-[10px] text-text-muted">{parentName(project, workspace.projects)}</span> : null}
                          {selectedProjectId === project.id ? <CheckIcon className="shrink-0 text-text" size={12} /> : null}
                        </span>
                      </span>
                    </button>
                  ))}
                  {!visibleProjects.length ? <p className="px-4 py-5 text-center text-sm text-text-muted">no match</p> : null}
                </div>
              </div>
            ) : null}
          </>
        ) : (
          <>
            <div className="flex items-center gap-3 border-b border-border px-4 py-3">
              <SearchIcon className="shrink-0 text-text-muted" size={16} />
              <input
                ref={searchInputRef}
                aria-label="search or create a task..."
                className="flex-1 bg-transparent text-sm text-text outline-none placeholder:text-text-muted/60"
                onChange={(event) => {
                  setQuery(event.target.value);
                  setSelectedIndex(0);
                  updateAtSuggestions(event.target.value, 'search');
                }}
                placeholder="search or create a task..."
                value={query}
              />
              <kbd className="hidden rounded border border-border bg-surface px-1.5 py-0.5 font-mono text-[10px] text-text-muted md:inline">esc</kbd>
            </div>
            {showAtSuggestions ? <div className="border-b border-border"><SuggestionList items={atSuggestions} selectedIndex={atSelectedIndex} onSelect={applyAtSuggestion} /></div> : null}

            <div className="scrollbar-thin max-h-[50vh] overflow-y-auto">
              {query.trim() && results.length ? (
                <>
                  {createFirst ? <CreateResult active={selectedIndex === 0} query={query} onClick={startCreate} prominent /> : null}
                  {projectResults.length ? <ResultGroup label="projects">{projectResults.map((result) => <ResultButton active={results.indexOf(result) === selectedIndex} key={result.id} onClick={() => activate(result)}><span className="h-2 w-2 shrink-0 rounded-full" style={{ background: workspace.projects.find((project) => project.id === result.id)?.color ?? '#525252' }} /><span className="truncate text-sm">{result.title}</span><ChevronRightIcon className="ml-auto shrink-0 text-text-muted" size={12} /></ResultButton>)}</ResultGroup> : null}
                  {taskResults.length ? <ResultGroup label="tasks">{taskResults.map((result) => <ResultButton active={results.indexOf(result) === selectedIndex} key={result.id} onClick={() => activate(result)}><span className="h-1.5 w-1.5 shrink-0 rounded-full bg-text-muted" /><span className={`truncate text-sm ${result.isDone ? 'line-through opacity-50' : ''}`}>{result.title}</span>{result.projectName ? <span className="ml-auto max-w-[120px] shrink-0 truncate text-[10px] text-text-muted">{result.projectName}</span> : null}</ResultButton>)}</ResultGroup> : null}
                  {!createFirst ? <CreateResult active={results.findIndex((result) => result.type === 'create') === selectedIndex} query={query} onClick={startCreate} /> : null}
                  <div className="h-1" />
                </>
              ) : !query.trim() ? <p className="px-4 py-8 text-center text-xs text-text-muted">type to search or create</p> : null}
            </div>
            {results.length ? <footer className="hidden items-center gap-4 border-t border-border px-4 py-2 text-[10px] text-text-muted md:flex"><span><kbd className="rounded border border-border bg-surface px-1 py-0.5 font-mono">↑↓</kbd> navigate</span><span><kbd className="rounded border border-border bg-surface px-1 py-0.5 font-mono">↵</kbd> open</span></footer> : null}
          </>
        )}
      </section>
    </div>
  );
}

function buildResults(query: string, projects: Project[], tasks: WorkspaceModel['tasks']): Result[] {
  const value = query.trim();
  if (!value) return [];
  const items: Result[] = [];
  for (const project of projects) {
    if (matches(project.title, value)) items.push({ type: 'project', id: project.id, title: project.title });
  }
  for (const task of tasks) {
    if (matches(task.title, value) || (task.description && matches(task.description, value))) {
      items.push({
        type: 'task',
        id: task.id,
        title: task.title,
        projectId: task.project_id,
        projectName: projects.find((project) => project.id === task.project_id)?.title,
        isDone: task.is_done,
      });
    }
  }
  const searchResults = items.slice(0, 12);
  const create: Result = { type: 'create', id: '__create__', title: value };
  return items.some((item) => item.type === 'project') ? [...searchResults, create] : [create, ...searchResults];
}

function matches(text: string, query: string) {
  const haystack = text.toLowerCase();
  const needle = query.toLowerCase();
  if (haystack.includes(needle)) return true;
  let needleIndex = 0;
  for (let index = 0; index < haystack.length && needleIndex < needle.length; index += 1) {
    if (haystack[index] === needle[needleIndex]) needleIndex += 1;
  }
  return needleIndex === needle.length;
}

function parentName(project: Project, projects: Project[]) {
  return project.parent_id ? projects.find((candidate) => candidate.id === project.parent_id)?.title ?? null : null;
}

function DateChip({ value }: { value: string }) {
  const date = new Date(value);
  const time = date.getHours() || date.getMinutes() ? ` ${date.getHours()}h${date.getMinutes().toString().padStart(2, '0')}` : '';
  return <span className="shrink-0 rounded-md border border-border bg-surface px-1.5 py-0.5 text-[10px] text-text-muted">{date.toLocaleDateString('en', { month: 'short', day: 'numeric' })}{time}</span>;
}

function SuggestionList({ items, selectedIndex, onSelect }: { items: Suggestion[]; selectedIndex: number; onSelect: (suggestion: Suggestion) => void }) {
  return (
    <div className="overflow-hidden bg-elevated">
      {items.map((suggestion, index) => (
        <button className={`flex w-full items-center gap-3 px-4 py-2 text-left text-sm ${index === selectedIndex ? 'bg-surface text-text' : 'text-text-secondary hover:bg-surface/50'}`} key={`${suggestion.type}-${suggestion.value}`} onMouseDown={(event) => { event.preventDefault(); onSelect(suggestion); }} type="button">
          <span className="w-8 text-right text-[9px] font-medium uppercase tracking-wider text-text-muted">{suggestion.type === 'project' ? 'proj' : suggestion.type}</span>
          <span className="flex-1">{suggestion.label}</span>
          {suggestion.description ? <span className="text-[11px] text-text-muted">{suggestion.description}</span> : null}
        </button>
      ))}
    </div>
  );
}

function ResultGroup({ label, children }: { label: string; children: React.ReactNode }) {
  return <div><p className="px-4 pb-1 pt-2 text-[10px] font-medium uppercase tracking-wider text-text-muted">{label}</p>{children}</div>;
}

function ResultButton({ active, onClick, children }: { active: boolean; onClick: () => void; children: React.ReactNode }) {
  return <button className="block w-full px-3 py-0.5 text-left" onClick={onClick} type="button"><span className={`flex items-center gap-2.5 rounded-lg px-2 py-2 ${active ? 'bg-surface text-text' : 'text-text-secondary hover:bg-surface/50'}`}>{children}</span></button>;
}

function CreateResult({ active, query, onClick, prominent = false }: { active: boolean; query: string; onClick: () => void; prominent?: boolean }) {
  return <button className={`block w-full px-3 text-left ${prominent ? 'py-1' : 'mt-1 border-t border-border/50 py-1'}`} onClick={onClick} type="button"><span className={`flex items-center gap-2.5 rounded-lg px-2 ${prominent ? 'py-2.5' : 'py-2'} ${active ? 'bg-surface text-text' : 'text-text-muted hover:bg-surface/50 hover:text-text-secondary'}`}><PlusIcon size={prominent ? 14 : 12} /><span className={prominent ? 'text-sm' : 'text-[13px]'}>create {prominent ? <strong>“{query.trim()}”</strong> : `“${query.trim()}”`}</span></span></button>;
}

// frontend/src/lib/components/CommandPalette.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { page } from '$app/state';
	import { api, type Project, type Task } from '$lib/api';
	import { getDataStore } from '$lib/stores/data.svelte';
	import { parseInput, getSuggestions, type Suggestion } from '$lib/smart-input';
	import { tick } from 'svelte';

	let {
		open = $bindable(false),
	}: {
		open: boolean;
	} = $props();

	const store = getDataStore();

	let query = $state('');
	let selectedIdx = $state(0);
	let inputEl = $state<HTMLInputElement>();

	// @ suggestions
	let atSuggestions = $state<Suggestion[]>([]);
	let atSelectedIdx = $state(0);
	let showAtSuggestions = $state(false);
	let atSource = $state<'search' | 'create'>('search');

	function updateAtSuggestions(text: string, source: 'search' | 'create') {
		const words = text.split(/\s/);
		const last = words[words.length - 1];
		if (last.startsWith('@') && last.length > 1) {
			atSource = source;
			atSuggestions = getSuggestions(last.slice(1), []);
			atSelectedIdx = 0;
			showAtSuggestions = atSuggestions.length > 0;
		} else {
			showAtSuggestions = false;
		}
	}

	function onQueryInput() {
		updateAtSuggestions(query, 'search');
	}

	function onCreateTaskInput() {
		updateAtSuggestions(creatingTask, 'create');
	}

	function focusSoon(getEl: () => HTMLElement | undefined) {
		const focus = () => getEl()?.focus();
		focus();
		requestAnimationFrame(focus);
		setTimeout(focus, 0);
		setTimeout(focus, 50);
	}

	function applyAtSuggestion(s: Suggestion) {
		const text = atSource === 'create' ? creatingTask : query;
		const words = text.split(/\s/);
		words[words.length - 1] = `@${s.value}`;
		if (atSource === 'create') {
			creatingTask = words.join(' ') + ' ';
		} else {
			query = words.join(' ') + ' ';
		}
		showAtSuggestions = false;
		setTimeout(() => (atSource === 'create' ? createTaskInputEl : inputEl)?.focus(), 0);
	}

	// Step 2: picking a project for new task
	let creatingTask = $state('');
	let projectQuery = $state('');
	let projectIdx = $state(0);
	let selectedProjectId = $state<string | null>(null);
	let projectPickerOpen = $state(false);
	let createTaskInputEl = $state<HTMLInputElement>();
	let projectInputEl = $state<HTMLInputElement>();

	$effect(() => {
		if (open) {
			query = '';
			creatingTask = '';
			projectQuery = '';
			selectedProjectId = null;
			projectPickerOpen = false;
			selectedIdx = 0;
			projectIdx = 0;
			showAtSuggestions = false;
			setTimeout(() => inputEl?.focus(), 50);
		}
	});

	function matches(text: string, q: string): boolean {
		const lower = text.toLowerCase();
		const ql = q.toLowerCase();
		if (lower.includes(ql)) return true;
		let j = 0;
		for (let i = 0; i < lower.length && j < ql.length; i++) {
			if (lower[i] === ql[j]) j++;
		}
		return j === ql.length;
	}

	interface Result {
		type: 'project' | 'task' | 'create';
		id: string;
		title: string;
		projectId?: string;
		projectName?: string;
		isDone?: boolean;
	}

	let results = $derived.by(() => {
		const q = query.trim();
		if (!q) return [];
		const items: Result[] = [];
		for (const p of store.projects) {
			if (matches(p.title, q)) items.push({ type: 'project', id: p.id, title: p.title });
		}
		for (const t of store.allTasks) {
			if (matches(t.title, q) || (t.description && matches(t.description, q))) {
				const proj = store.projects.find(p => p.id === t.project_id);
				items.push({ type: 'task', id: t.id, title: t.title, projectId: t.project_id, projectName: proj?.title, isDone: t.is_done });
			}
		}
		const searchResults = items.slice(0, 12);
		// Add "create" as a navigable item
		const createItem: Result = { type: 'create', id: '__create__', title: q };
		// If no project matches, put create first (prioritize it)
		if (items.filter(r => r.type === 'project').length === 0) {
			return [createItem, ...searchResults];
		}
		return [...searchResults, createItem];
	});

	let projectResults = $derived(results.filter(r => r.type === 'project'));
	let taskResults = $derived(results.filter(r => r.type === 'task'));

	// Leaf projects only (no children = can hold tasks)
	let leafProjects = $derived.by(() => {
		const parentIds = new Set(store.projects.filter(p => p.parent_id).map(p => p.parent_id));
		const q = projectQuery.trim().toLowerCase();
		return store.projects
			.filter(p => !parentIds.has(p.id))
			.filter(p => !q || matches(p.title, q));
	});

	let selectedProject = $derived(
		selectedProjectId ? store.projects.find(p => p.id === selectedProjectId) : null
	);

	let visibleLeafProjects = $derived(
		projectQuery.trim() ? leafProjects.slice(0, 12) : leafProjects.slice(0, 7)
	);

	function activate(r: Result) {
		if (r.type === 'create') {
			startCreate();
			return;
		}
		const pid = r.type === 'project' ? r.id : r.projectId;
		open = false;
		if (page.url.pathname !== '/app') goto('/app');
		setTimeout(() => document.getElementById(`project-${pid}`)?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 200);
	}

	async function startCreate() {
		if (!query.trim()) return;
		creatingTask = query.trim();
		projectQuery = '';
		selectedProjectId = null;
		projectPickerOpen = true;
		projectIdx = 0;
		await tick();
		focusSoon(() => projectInputEl);
	}

	function onProjectInput() {
		projectIdx = 0;
		projectPickerOpen = true;
	}

	async function selectProject(projectId: string) {
		selectedProjectId = projectId;
		projectQuery = '';
		projectPickerOpen = false;
		await tick();
		const nextProjectIdx = leafProjects.findIndex(p => p.id === projectId);
		projectIdx = Math.max(nextProjectIdx, 0);
		focusSoon(() => createTaskInputEl);
	}

	async function openProjectPicker() {
		projectPickerOpen = true;
		await tick();
		focusSoon(() => projectInputEl);
	}

	async function submitCreatedTask() {
		const title = creatingTask.trim();
		if (!title) {
			createTaskInputEl?.focus();
			return;
		}
		if (!selectedProjectId) {
			projectInputEl?.focus();
			return;
		}
		const parsed = parseInput(creatingTask);
		const projectId = selectedProjectId;
		await store.addTask(projectId, { title: parsed.title || title, due_date: parsed.due_date });
		open = false;
		if (page.url.pathname !== '/app') goto('/app');
		setTimeout(() => document.getElementById(`project-${projectId}`)?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 200);
	}

	function onKeydown(e: KeyboardEvent) {
		if (e.key === 'Escape') {
			if (showAtSuggestions) { showAtSuggestions = false; return; }
			if (creatingTask && projectPickerOpen && selectedProjectId) {
				projectPickerOpen = false;
				projectQuery = '';
				setTimeout(() => createTaskInputEl?.focus(), 0);
			}
			else if (creatingTask) { creatingTask = ''; setTimeout(() => inputEl?.focus(), 50); }
			else open = false;
			return;
		}
		// @ suggestions take priority
		if (showAtSuggestions) {
			if (e.key === 'ArrowDown') { e.preventDefault(); atSelectedIdx = Math.min(atSelectedIdx + 1, atSuggestions.length - 1); return; }
			if (e.key === 'ArrowUp') { e.preventDefault(); atSelectedIdx = Math.max(atSelectedIdx - 1, 0); return; }
			if (e.key === 'Tab' || e.key === 'Enter') { e.preventDefault(); applyAtSuggestion(atSuggestions[atSelectedIdx]); return; }
		}
		if (creatingTask) {
			const target = e.target;
			const isTaskInput = target === createTaskInputEl;
			const isProjectInput = target === projectInputEl;
			if (e.key === 'ArrowDown') {
				e.preventDefault();
				projectPickerOpen = true;
				projectIdx = Math.min(projectIdx + 1, Math.max(visibleLeafProjects.length - 1, 0));
				if (!isProjectInput) projectInputEl?.focus();
				return;
			}
			if (e.key === 'ArrowUp') {
				e.preventDefault();
				projectPickerOpen = true;
				projectIdx = Math.max(projectIdx - 1, 0);
				if (!isProjectInput) projectInputEl?.focus();
				return;
			}
			if (projectPickerOpen && (e.key === 'Tab' || e.key === 'Enter') && visibleLeafProjects[projectIdx]) {
				e.preventDefault();
				selectProject(visibleLeafProjects[projectIdx].id);
				return;
			}
			if (isTaskInput && e.key === 'Enter') {
				e.preventDefault();
				if (!selectedProjectId) {
					openProjectPicker();
					return;
				}
				submitCreatedTask();
				return;
			}
			if (isTaskInput && e.key === 'Tab' && !e.shiftKey && !selectedProjectId) {
				e.preventDefault();
				openProjectPicker();
				return;
			}
			return;
		}
		// Step 1: search
		if (e.key === 'ArrowDown') { e.preventDefault(); selectedIdx = Math.min(selectedIdx + 1, results.length - 1); }
		if (e.key === 'ArrowUp') { e.preventDefault(); selectedIdx = Math.max(selectedIdx - 1, 0); }
		if (e.key === 'Enter' || e.key === 'Tab') {
			e.preventDefault();
			if (results[selectedIdx]) activate(results[selectedIdx]);
			else if (query.trim()) startCreate();
		}
	}

	function flatIndex(r: Result): number {
		return results.indexOf(r);
	}

	function parentName(p: Project): string | null {
		if (!p.parent_id) return null;
		return store.projects.find(pp => pp.id === p.parent_id)?.title || null;
	}
</script>

{#if open}
	<!-- svelte-ignore a11y_click_events_have_key_events -->
	<!-- svelte-ignore a11y_no_static_element_interactions -->
	<div class="fixed inset-0 bg-black/50 z-[60] backdrop-blur-[3px] animate-fadeIn" onclick={() => open = false}></div>

	<!-- svelte-ignore a11y_no_static_element_interactions -->
	<div class="fixed inset-0 z-[70] flex items-start justify-center pt-[15vh] px-4 pointer-events-none" onkeydown={onKeydown}>
		<div class="bg-bg border border-border rounded-2xl shadow-2xl w-full max-w-xl pointer-events-auto animate-modalIn overflow-hidden">

				{#if creatingTask}
					{@const parsedPreview = parseInput(creatingTask)}
					<div class="px-4 pt-4 pb-3 border-b border-border/70">
						<div class="flex items-center gap-2">
							<input
								bind:this={createTaskInputEl}
								bind:value={creatingTask}
								oninput={onCreateTaskInput}
								placeholder="new task..."
								class="flex-1 min-w-0 bg-transparent text-[15px] leading-6 text-text placeholder:text-text-muted/60 focus:outline-none"
							/>
							{#if parsedPreview.due_date}
								{@const d = new Date(parsedPreview.due_date)}
								<span class="text-[10px] text-text-muted bg-surface border border-border rounded-md px-1.5 py-0.5 flex-shrink-0">
									{d.toLocaleDateString('en', { month: 'short', day: 'numeric' })}{d.getHours() || d.getMinutes() ? ` ${d.getHours()}h${d.getMinutes().toString().padStart(2, '0')}` : ''}
								</span>
							{/if}
						</div>

						{#if showAtSuggestions && atSource === 'create'}
							<div class="mt-2 -mx-1 overflow-hidden rounded-lg border border-border bg-elevated shadow-sm">
								{#each atSuggestions as s, i}
									<!-- svelte-ignore a11y_click_events_have_key_events -->
									<!-- svelte-ignore a11y_no_static_element_interactions -->
									<div
										class="px-3 py-2 text-sm flex items-center gap-3 cursor-pointer transition-colors {i === atSelectedIdx ? 'bg-surface text-text' : 'text-text-secondary hover:bg-surface/50'}"
										onmousedown={() => applyAtSuggestion(s)}
									>
										<span class="text-[9px] uppercase tracking-wider text-text-muted w-8 text-right font-medium">{s.type === 'date' ? 'date' : s.type === 'time' ? 'time' : 'proj'}</span>
										<span class="flex-1">{s.label}</span>
										{#if s.description}
											<span class="text-[11px] text-text-muted">{s.description}</span>
										{/if}
									</div>
								{/each}
							</div>
						{/if}

						<div class="mt-3 flex items-center gap-2">
							<button
								type="button"
								onclick={openProjectPicker}
								class="min-w-0 inline-flex items-center gap-1.5 rounded-md border border-border bg-surface/60 px-2 py-1 text-xs text-text-secondary hover:text-text hover:bg-surface transition-colors"
							>
								{#if selectedProject}
									<span class="w-1.5 h-1.5 rounded-full flex-shrink-0" style="background:{selectedProject.color || '#525252'}"></span>
									<span class="truncate max-w-[220px]">{selectedProject.title}</span>
								{:else}
									<span class="w-1.5 h-1.5 rounded-full flex-shrink-0 bg-text-muted"></span>
									<span>project</span>
								{/if}
							</button>
						</div>
					</div>

					{#if projectPickerOpen || !selectedProjectId}
						<div class="border-b border-border/70">
							<div class="px-4 py-2">
								<input
									bind:this={projectInputEl}
									bind:value={projectQuery}
									oninput={onProjectInput}
									placeholder={selectedProject ? 'change project...' : 'project...'}
									class="w-full bg-transparent text-sm text-text placeholder:text-text-muted/60 focus:outline-none"
								/>
							</div>

							<div class="max-h-[34vh] overflow-y-auto pb-1">
								{#each visibleLeafProjects as p, i}
									<!-- svelte-ignore a11y_click_events_have_key_events -->
									<!-- svelte-ignore a11y_no_static_element_interactions -->
									<div class="px-3 py-0.5" onclick={() => selectProject(p.id)}>
										<div class="flex items-center gap-2.5 px-2 py-2 rounded-md cursor-pointer transition-colors {i === projectIdx ? 'bg-surface text-text' : selectedProjectId === p.id ? 'text-text bg-surface/60' : 'text-text-secondary hover:bg-surface/50'}">
											<span class="w-1.5 h-1.5 rounded-full flex-shrink-0" style="background:{p.color || '#525252'}"></span>
											<span class="text-sm truncate">{p.title}</span>
											<div class="ml-auto flex items-center gap-2 min-w-0">
												{#if parentName(p)}
													<span class="text-[10px] text-text-muted truncate max-w-[110px]">{parentName(p)}</span>
												{/if}
												{#if selectedProjectId === p.id}
													<svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round" class="text-text flex-shrink-0"><polyline points="20 6 9 17 4 12"/></svg>
												{/if}
											</div>
										</div>
									</div>
								{/each}
								{#if visibleLeafProjects.length === 0}
									<div class="px-4 py-5 text-center">
										<p class="text-sm text-text-muted">no match</p>
									</div>
								{/if}
							</div>
						</div>
					{/if}

				{:else}
				<!-- Step 1: Search -->
				<div class="px-4 py-3 border-b border-border flex items-center gap-3">
					<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" class="text-text-muted flex-shrink-0">
						<circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/>
					</svg>
					<input
						bind:this={inputEl}
						bind:value={query}
						oninput={onQueryInput}
						placeholder="search or create a task..."
						class="flex-1 bg-transparent text-sm text-text placeholder:text-text-muted/60 focus:outline-none"
					/>
					<kbd class="hidden md:inline text-[10px] text-text-muted bg-surface border border-border rounded px-1.5 py-0.5 font-mono">esc</kbd>
				</div>

				{#if showAtSuggestions}
					<div class="border-b border-border">
						{#each atSuggestions as s, i}
							<!-- svelte-ignore a11y_click_events_have_key_events -->
							<!-- svelte-ignore a11y_no_static_element_interactions -->
							<div
								class="px-4 py-2 text-sm flex items-center gap-3 cursor-pointer transition-colors {i === atSelectedIdx ? 'bg-surface text-text' : 'text-text-secondary hover:bg-surface/50'}"
								onmousedown={() => applyAtSuggestion(s)}
							>
								<span class="text-[9px] uppercase tracking-wider text-text-muted w-8 text-right font-medium">{s.type === 'date' ? 'date' : s.type === 'time' ? 'time' : 'proj'}</span>
								<span class="flex-1">{s.label}</span>
								{#if s.description}
									<span class="text-[11px] text-text-muted">{s.description}</span>
								{/if}
							</div>
						{/each}
					</div>
				{/if}

				<div class="max-h-[50vh] overflow-y-auto">
					{#if query.trim() && results.length > 0}
						{@const createFirst = results[0]?.type === 'create'}
						{#if createFirst}
							<!-- Create is first (no project match) -->
							<!-- svelte-ignore a11y_click_events_have_key_events -->
							<!-- svelte-ignore a11y_no_static_element_interactions -->
							<div class="px-3 py-1" onclick={startCreate}>
								<div class="flex items-center gap-2.5 px-2 py-2.5 rounded-lg cursor-pointer transition-colors {0 === selectedIdx ? 'bg-surface text-text' : 'text-text-muted hover:bg-surface/50 hover:text-text-secondary'}">
									<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" class="flex-shrink-0">
										<line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/>
									</svg>
									<span class="text-sm">create <strong>"{query.trim()}"</strong></span>
								</div>
							</div>
						{/if}

						{#if projectResults.length > 0}
							<div class="px-3 pt-2 pb-1">
								<p class="text-[10px] uppercase tracking-wider text-text-muted font-medium px-1">projects</p>
							</div>
							{#each projectResults as r}
								<!-- svelte-ignore a11y_click_events_have_key_events -->
								<!-- svelte-ignore a11y_no_static_element_interactions -->
								<div class="px-3 py-0.5" onclick={() => activate(r)}>
									<div class="flex items-center gap-2.5 px-2 py-2 rounded-lg cursor-pointer transition-colors {flatIndex(r) === selectedIdx ? 'bg-surface text-text' : 'text-text-secondary hover:bg-surface/50'}">
										<span class="w-2 h-2 rounded-full flex-shrink-0" style="background:{store.projects.find(p => p.id === r.id)?.color || '#525252'}"></span>
										<span class="text-sm truncate">{r.title}</span>
										<svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" class="ml-auto text-text-muted flex-shrink-0"><polyline points="9 18 15 12 9 6"/></svg>
									</div>
								</div>
							{/each}
						{/if}

						{#if taskResults.length > 0}
							<div class="px-3 pt-2 pb-1">
								<p class="text-[10px] uppercase tracking-wider text-text-muted font-medium px-1">tasks</p>
							</div>
							{#each taskResults as r}
								<!-- svelte-ignore a11y_click_events_have_key_events -->
								<!-- svelte-ignore a11y_no_static_element_interactions -->
								<div class="px-3 py-0.5" onclick={() => activate(r)}>
									<div class="flex items-center gap-2.5 px-2 py-2 rounded-lg cursor-pointer transition-colors {flatIndex(r) === selectedIdx ? 'bg-surface text-text' : 'text-text-secondary hover:bg-surface/50'}">
										<span class="w-1.5 h-1.5 rounded-full flex-shrink-0 bg-text-muted"></span>
										<span class="text-sm truncate {r.isDone ? 'line-through opacity-50' : ''}">{r.title}</span>
										{#if r.projectName}
											<span class="text-[10px] text-text-muted ml-auto truncate max-w-[120px] flex-shrink-0">{r.projectName}</span>
										{/if}
									</div>
								</div>
							{/each}
						{/if}

						{#if !createFirst}
							<!-- Create is last (projects matched) -->
							{@const createIdx = results.findIndex(r => r.type === 'create')}
							<!-- svelte-ignore a11y_click_events_have_key_events -->
							<!-- svelte-ignore a11y_no_static_element_interactions -->
							<div class="px-3 py-0.5 border-t border-border/50 mt-1 pt-1" onclick={startCreate}>
								<div class="flex items-center gap-2.5 px-2 py-2 rounded-lg cursor-pointer transition-colors {createIdx === selectedIdx ? 'bg-surface text-text' : 'text-text-muted hover:bg-surface/50 hover:text-text-secondary'}">
									<svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" class="flex-shrink-0">
										<line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/>
									</svg>
									<span class="text-[13px]">create "{query.trim()}"</span>
								</div>
							</div>
						{/if}

						<div class="h-1"></div>
					{:else if !query.trim()}
						<div class="px-4 py-8 text-center">
							<p class="text-xs text-text-muted">type to search or create</p>
						</div>
					{/if}
				</div>

				{#if results.length > 0}
					<div class="hidden md:flex px-4 py-2 border-t border-border items-center gap-4 text-[10px] text-text-muted">
						<span><kbd class="font-mono bg-surface border border-border rounded px-1 py-0.5">↑↓</kbd> navigate</span>
						<span><kbd class="font-mono bg-surface border border-border rounded px-1 py-0.5">↵</kbd> open</span>
					</div>
				{/if}
			{/if}
		</div>
	</div>
{/if}

<style>
	.animate-fadeIn { animation: fadeIn 0.1s ease; }
	.animate-modalIn { animation: modalIn 0.15s cubic-bezier(0, 0, 0.2, 1); }
	@keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }
	@keyframes modalIn {
		from { opacity: 0; transform: translateY(-4px) scale(0.98); }
		to { opacity: 1; transform: translateY(0) scale(1); }
	}
</style>
