// frontend/src/features/workspace/components/DatePicker.tsx
import { useEffect, useMemo, useRef, useState } from 'react';
import { createPortal } from 'react-dom';

import { CalendarIcon, ChevronLeftIcon, ChevronRightIcon, ClockIcon } from '@/components/icons';
import { relativeDate, timeLabel } from '@/features/workspace/utils/dates';

interface DatePickerProps {
  value: string | null;
  onChange: (value: string | null) => unknown | Promise<unknown>;
}

export function DatePicker({ value, onChange }: DatePickerProps) {
  const triggerRef = useRef<HTMLButtonElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);
  const [open, setOpen] = useState(false);
  const [textInput, setTextInput] = useState('');
  const [viewDate, setViewDate] = useState(() => (value ? new Date(value) : new Date()));
  const [position, setPosition] = useState<React.CSSProperties>({});
  const [isMobile, setIsMobile] = useState(false);
  const timeValue = value ? formatInputTime(new Date(value)) : '';

  const calendarDays = useMemo(() => {
    const firstDay = new Date(viewDate.getFullYear(), viewDate.getMonth(), 1).getDay();
    const daysInMonth = new Date(viewDate.getFullYear(), viewDate.getMonth() + 1, 0).getDate();
    return [
      ...Array<number | null>(firstDay === 0 ? 6 : firstDay - 1).fill(null),
      ...Array.from({ length: daysInMonth }, (_, index) => index + 1),
    ];
  }, [viewDate]);

  useEffect(() => {
    if (!open) return;
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape') setOpen(false);
    };
    window.addEventListener('keydown', onKeyDown);
    return () => window.removeEventListener('keydown', onKeyDown);
  }, [open]);

  const openPicker = () => {
    if (open) {
      setOpen(false);
      setTextInput('');
      return;
    }
    const mobile = window.innerWidth < 768;
    setIsMobile(mobile);
    if (!mobile && triggerRef.current) {
      const rect = triggerRef.current.getBoundingClientRect();
      const goUp = window.innerHeight - rect.bottom < 350;
      setPosition(
        goUp
          ? { position: 'fixed', bottom: window.innerHeight - rect.top + 4, left: Math.min(rect.left, window.innerWidth - 272) }
          : { position: 'fixed', top: rect.bottom + 4, left: Math.min(rect.left, window.innerWidth - 272) },
      );
    }
    setViewDate(value ? new Date(value) : new Date());
    setOpen(true);
    window.setTimeout(() => inputRef.current?.focus(), 50);
  };

  const setDate = async (date: Date | null) => {
    await onChange(date?.toISOString() ?? null);
    setOpen(false);
    setTextInput('');
  };

  const setRelativeDate = (days: number) => {
    const date = new Date();
    date.setDate(date.getDate() + days);
    date.setHours(9, 0, 0, 0);
    void setDate(date);
  };

  const setNextMonday = () => {
    const date = new Date();
    const difference = date.getDay() === 0 ? 1 : 8 - date.getDay();
    date.setDate(date.getDate() + difference);
    date.setHours(9, 0, 0, 0);
    void setDate(date);
  };

  const applyTime = (time: string) => {
    if (!value || !time) return;
    const [hours, minutes] = time.split(':').map(Number);
    const date = new Date(value);
    date.setHours(hours, minutes, 0, 0);
    void onChange(date.toISOString());
  };

  const clearTime = () => {
    if (!value) return;
    const date = new Date(value);
    date.setHours(0, 0, 0, 0);
    void onChange(date.toISOString());
  };

  const submitText = () => {
    const date = parseTextDate(textInput, value);
    if (date) void setDate(date);
  };

  return (
    <div>
      <button
        ref={triggerRef}
        className={`flex items-center gap-1.5 rounded-lg border px-2.5 py-1 text-xs transition ${
          value ? 'border-border-strong bg-surface text-text' : 'border-border text-text-muted hover:bg-surface/60 hover:text-text-secondary'
        }`}
        onClick={openPicker}
        type="button"
      >
        <CalendarIcon size={12} />
        {value ? `${relativeDate(value, { long: true })}${timeLabel(value) ? ` ${timeLabel(value)}` : ''}` : 'set date'}
      </button>

      {open
        ? createPortal(
            <>
              <button
                aria-label="close date picker"
                className={`fixed inset-0 z-[75] ${isMobile ? 'bg-black/50 backdrop-blur-[2px]' : ''}`}
                data-floating-overlay="true"
                onClick={() => setOpen(false)}
                type="button"
              />
              <section
                className={`${isMobile ? 'modal-in fixed inset-x-0 bottom-0 z-[80] w-full rounded-t-2xl safe-bottom' : 'modal-in z-[80] w-64 rounded-xl'} overflow-hidden border border-border bg-elevated shadow-2xl`}
                data-floating-overlay="true"
                onClick={(event) => event.stopPropagation()}
                style={isMobile ? undefined : position}
              >
                <div className="flex flex-wrap gap-1.5 border-b border-border p-2">
                  <QuickDate label="today" onClick={() => setRelativeDate(0)} />
                  <QuickDate label="tomorrow" onClick={() => setRelativeDate(1)} />
                  <QuickDate label="monday" onClick={setNextMonday} />
                  <QuickDate label="next week" onClick={() => setRelativeDate(7)} />
                  {value ? <button className="rounded-lg px-2.5 py-1 text-xs text-text-muted hover:text-danger" onClick={() => void setDate(null)} type="button">clear</button> : null}
                </div>

                <div className="border-b border-border p-2">
                  <input
                    ref={inputRef}
                    className="field !rounded-lg !px-2.5 !py-1.5 !text-xs"
                    onChange={(event) => setTextInput(event.target.value)}
                    onKeyDown={(event) => {
                      if (event.key === 'Enter') {
                        event.preventDefault();
                        submitText();
                      }
                    }}
                    placeholder="fri, 3d, jun 15, 15h, 3pm..."
                    value={textInput}
                  />
                </div>

                {value ? (
                  <div className="flex items-center gap-2 border-b border-border px-2 py-1.5">
                    <ClockIcon className="shrink-0 text-text-muted" size={11} />
                    <div className="flex gap-1">
                      {['09:00', '12:00', '14:00', '17:00'].map((time) => (
                        <button
                          className={`rounded px-1.5 py-0.5 text-[10px] ${timeValue === time ? 'bg-accent text-accent-fg' : 'bg-surface text-text-muted hover:text-text'}`}
                          key={time}
                          onClick={() => applyTime(time)}
                          type="button"
                        >
                          {time.replace(':00', 'h')}
                        </button>
                      ))}
                    </div>
                    <input className="ml-auto w-[76px] rounded border border-border bg-surface px-1.5 py-0.5 text-[10px] text-text outline-none" onChange={(event) => applyTime(event.target.value)} type="time" value={timeValue} />
                    {timeValue ? <button className="text-[10px] text-text-muted hover:text-danger" onClick={clearTime} type="button">×</button> : null}
                  </div>
                ) : null}

                <div className="p-2">
                  <div className="mb-2 flex items-center justify-between px-1">
                    <button aria-label="previous month" className="icon-button !h-5 !w-5" onClick={() => setViewDate(new Date(viewDate.getFullYear(), viewDate.getMonth() - 1, 1))} type="button"><ChevronLeftIcon size={10} /></button>
                    <span className="text-[11px] font-medium text-text-secondary">{viewDate.toLocaleDateString('en', { month: 'long', year: 'numeric' }).toLowerCase()}</span>
                    <button aria-label="next month" className="icon-button !h-5 !w-5" onClick={() => setViewDate(new Date(viewDate.getFullYear(), viewDate.getMonth() + 1, 1))} type="button"><ChevronRightIcon size={10} /></button>
                  </div>
                  <div className="mb-1 grid grid-cols-7">
                    {['m', 't', 'w', 't', 'f', 's', 's'].map((day, index) => <div className="py-0.5 text-center text-[9px] text-text-muted" key={`${day}-${index}`}>{day}</div>)}
                  </div>
                  <div className="grid grid-cols-7">
                    {calendarDays.map((day, index) =>
                      day ? (
                        <button
                          className={`aspect-square rounded-md text-[11px] transition ${isSelected(day, viewDate, value) ? 'bg-accent font-medium text-accent-fg' : isToday(day, viewDate) ? 'font-medium text-text ring-1 ring-border-strong' : 'text-text-secondary hover:bg-surface hover:text-text'}`}
                          key={`${day}-${index}`}
                          onClick={() => void setDate(new Date(viewDate.getFullYear(), viewDate.getMonth(), day, 9, 0, 0))}
                          type="button"
                        >
                          {day}
                        </button>
                      ) : <span key={`empty-${index}`} />,
                    )}
                  </div>
                </div>
              </section>
            </>,
            document.body,
          )
        : null}
    </div>
  );
}

function QuickDate({ label, onClick }: { label: string; onClick: () => void }) {
  return <button className="rounded-lg bg-surface px-2.5 py-1 text-xs text-text-secondary hover:bg-tertiary hover:text-text" onClick={onClick} type="button">{label}</button>;
}

function formatInputTime(date: Date) {
  const hours = date.getHours();
  const minutes = date.getMinutes();
  return hours || minutes ? `${hours.toString().padStart(2, '0')}:${minutes.toString().padStart(2, '0')}` : '';
}

function isToday(day: number, viewDate: Date) {
  const today = new Date();
  return day === today.getDate() && viewDate.getMonth() === today.getMonth() && viewDate.getFullYear() === today.getFullYear();
}

function isSelected(day: number, viewDate: Date, value: string | null) {
  if (!value) return false;
  const selected = new Date(value);
  return day === selected.getDate() && viewDate.getMonth() === selected.getMonth() && viewDate.getFullYear() === selected.getFullYear();
}

function parseTextDate(text: string, currentValue: string | null): Date | null {
  const value = text.trim().toLowerCase();
  if (!value) return null;
  const addDays = (days: number) => {
    const date = new Date();
    date.setDate(date.getDate() + days);
    date.setHours(9, 0, 0, 0);
    return date;
  };
  const nextWeekday = (day: number) => {
    const date = new Date();
    let difference = day - date.getDay();
    if (difference <= 0) difference += 7;
    date.setDate(date.getDate() + difference);
    date.setHours(9, 0, 0, 0);
    return date;
  };
  const aliases: Record<string, () => Date> = {
    today: () => addDays(0),
    "aujourd'hui": () => addDays(0),
    tomorrow: () => addDays(1),
    demain: () => addDays(1),
    monday: () => nextWeekday(1), lundi: () => nextWeekday(1),
    tuesday: () => nextWeekday(2), mardi: () => nextWeekday(2),
    wednesday: () => nextWeekday(3), mercredi: () => nextWeekday(3),
    thursday: () => nextWeekday(4), jeudi: () => nextWeekday(4),
    friday: () => nextWeekday(5), vendredi: () => nextWeekday(5),
    saturday: () => nextWeekday(6), samedi: () => nextWeekday(6),
    sunday: () => nextWeekday(0), dimanche: () => nextWeekday(0),
  };
  if (aliases[value]) return aliases[value]();
  const relative = value.match(/^(\d+)\s*(d|j|w|s)$/);
  if (relative) return addDays(Number(relative[1]) * (relative[2] === 'w' || relative[2] === 's' ? 7 : 1));
  const time = value.match(/^(\d{1,2})h(\d{2})?$/) ?? value.match(/^(\d{1,2}):(\d{2})$/);
  if (time && currentValue) {
    const date = new Date(currentValue);
    date.setHours(Number(time[1]), Number(time[2] ?? 0), 0, 0);
    return date;
  }
  const ampm = value.match(/^(\d{1,2})(am|pm)$/);
  if (ampm && currentValue) {
    let hours = Number(ampm[1]);
    if (ampm[2] === 'pm' && hours < 12) hours += 12;
    if (ampm[2] === 'am' && hours === 12) hours = 0;
    const date = new Date(currentValue);
    date.setHours(hours, 0, 0, 0);
    return date;
  }
  const parsed = new Date(text);
  return Number.isNaN(parsed.getTime()) ? null : parsed;
}

// frontend/src/lib/components/DatePicker.svelte
<script lang="ts">
	import { relativeDate, timeLabel } from '$lib/utils';

	let {
		value = $bindable<string | null>(null),
		onchange,
	}: {
		value: string | null;
		onchange?: (date: string | null) => void;
	} = $props();

	let open = $state(false);
	let textInput = $state('');
	let inputEl = $state<HTMLInputElement>();
	let timeValue = $state('');

	// Current displayed month for calendar
	let viewDate = $state(new Date());

	// Sync timeValue when value changes
	$effect(() => {
		if (value) {
			const d = new Date(value);
			const h = d.getHours();
			const m = d.getMinutes();
			timeValue = (h || m) ? `${h.toString().padStart(2, '0')}:${m.toString().padStart(2, '0')}` : '';
		} else {
			timeValue = '';
		}
	});

	let displayValue = $derived.by(() => {
		if (!value) return '';
		const datePart = relativeDate(value, { long: true });
		const time = timeLabel(value);
		return time ? `${datePart} ${time}` : datePart;
	});

	function applyTime(timeStr: string) {
		if (!value || !timeStr) return;
		const [h, m] = timeStr.split(':').map(Number);
		const d = new Date(value);
		d.setHours(h, m, 0, 0);
		value = d.toISOString();
		onchange?.(value);
	}

	function clearTime() {
		if (!value) return;
		const d = new Date(value);
		d.setHours(0, 0, 0, 0);
		timeValue = '';
		value = d.toISOString();
		onchange?.(value);
	}

	function setDate(d: Date | null) {
		value = d?.toISOString() || null;
		onchange?.(value);
		open = false;
		textInput = '';
	}

	function addDays(n: number): Date {
		const d = new Date();
		d.setDate(d.getDate() + n);
		d.setHours(9, 0, 0, 0);
		return d;
	}

	function nextMonday(): Date {
		const d = new Date();
		const day = d.getDay();
		const diff = day === 0 ? 1 : 8 - day;
		d.setDate(d.getDate() + diff);
		d.setHours(9, 0, 0, 0);
		return d;
	}

	function parseText(text: string): Date | null {
		const lower = text.trim().toLowerCase();
		if (!lower) return null;
		const map: Record<string, () => Date> = {
			'today': () => addDays(0),
			"aujourd'hui": () => addDays(0),
			'tomorrow': () => addDays(1),
			'demain': () => addDays(1),
			'monday': () => nextWeekday(1), 'lundi': () => nextWeekday(1),
			'tuesday': () => nextWeekday(2), 'mardi': () => nextWeekday(2),
			'wednesday': () => nextWeekday(3), 'mercredi': () => nextWeekday(3),
			'thursday': () => nextWeekday(4), 'jeudi': () => nextWeekday(4),
			'friday': () => nextWeekday(5), 'vendredi': () => nextWeekday(5),
			'saturday': () => nextWeekday(6), 'samedi': () => nextWeekday(6),
			'sunday': () => nextWeekday(0), 'dimanche': () => nextWeekday(0),
		};
		if (map[lower]) return map[lower]();
		// Try relative: "3d", "2j", "1w"
		const rel = lower.match(/^(\d+)\s*(d|j|w|s)$/);
		if (rel) {
			const n = parseInt(rel[1]);
			const unit = rel[2];
			if (unit === 'w' || unit === 's') return addDays(n * 7);
			return addDays(n);
		}
		// Try time only: "15h", "14h30", "3pm", "15:30"
		const timeMatch = lower.match(/^(\d{1,2})h(\d{2})?$/) || lower.match(/^(\d{1,2}):(\d{2})$/);
		if (timeMatch && value) {
			const d = new Date(value);
			d.setHours(parseInt(timeMatch[1]), timeMatch[2] ? parseInt(timeMatch[2]) : 0, 0, 0);
			return d;
		}
		const ampm = lower.match(/^(\d{1,2})(am|pm)$/i);
		if (ampm && value) {
			let h = parseInt(ampm[1]);
			if (ampm[2].toLowerCase() === 'pm' && h < 12) h += 12;
			if (ampm[2].toLowerCase() === 'am' && h === 12) h = 0;
			const d = new Date(value);
			d.setHours(h, 0, 0, 0);
			return d;
		}
		// Try parsing as date
		const parsed = new Date(text);
		if (!isNaN(parsed.getTime())) return parsed;
		return null;
	}

	function nextWeekday(day: number): Date {
		const d = new Date();
		const current = d.getDay();
		let diff = day - current;
		if (diff <= 0) diff += 7;
		d.setDate(d.getDate() + diff);
		d.setHours(9, 0, 0, 0);
		return d;
	}

	function handleTextSubmit() {
		const d = parseText(textInput);
		if (d) setDate(d);
	}

	// Calendar helpers
	let calendarDays = $derived.by(() => {
		const year = viewDate.getFullYear();
		const month = viewDate.getMonth();
		const firstDay = new Date(year, month, 1).getDay();
		const daysInMonth = new Date(year, month + 1, 0).getDate();
		const days: (number | null)[] = [];
		// Pad start
		for (let i = 0; i < (firstDay === 0 ? 6 : firstDay - 1); i++) days.push(null);
		for (let i = 1; i <= daysInMonth; i++) days.push(i);
		return days;
	});

	let monthLabel = $derived(viewDate.toLocaleDateString('en', { month: 'long', year: 'numeric' }).toLowerCase());

	function isToday(day: number): boolean {
		const now = new Date();
		return day === now.getDate() && viewDate.getMonth() === now.getMonth() && viewDate.getFullYear() === now.getFullYear();
	}

	function isSelected(day: number): boolean {
		if (!value) return false;
		const sel = new Date(value);
		return day === sel.getDate() && viewDate.getMonth() === sel.getMonth() && viewDate.getFullYear() === sel.getFullYear();
	}

	function selectDay(day: number) {
		const d = new Date(viewDate.getFullYear(), viewDate.getMonth(), day, 9, 0, 0);
		setDate(d);
	}

	let triggerEl: HTMLButtonElement;
	let popoverStyle = $state('');

	let isMobile = $state(false);

	function checkMobile() {
		isMobile = window.innerWidth < 768;
	}

	function openPicker() {
		if (open) { open = false; textInput = ''; return; }
		checkMobile();
		if (!isMobile && triggerEl) {
			const rect = triggerEl.getBoundingClientRect();
			const spaceBelow = window.innerHeight - rect.bottom;
			const goUp = spaceBelow < 350;
			popoverStyle = goUp
				? `position:fixed; bottom:${window.innerHeight - rect.top + 4}px; left:${rect.left}px;`
				: `position:fixed; top:${rect.bottom + 4}px; left:${rect.left}px;`;
		} else {
			popoverStyle = '';
		}
		open = true;
		setTimeout(() => inputEl?.focus(), 50);
	}

	function prevMonth() { viewDate = new Date(viewDate.getFullYear(), viewDate.getMonth() - 1, 1); }
	function nextMonth() { viewDate = new Date(viewDate.getFullYear(), viewDate.getMonth() + 1, 1); }
</script>

<div>
	<!-- Trigger -->
	<button
		bind:this={triggerEl}
		type="button"
		onclick={openPicker}
		class="flex items-center gap-1.5 px-2.5 py-1 rounded-lg text-xs transition-all border {value ? 'bg-surface border-border-strong text-text' : 'border-border text-text-muted hover:text-text-secondary hover:bg-surface/50'}"
	>
		<svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round">
			<rect x="3" y="4" width="18" height="18" rx="2"/><line x1="16" y1="2" x2="16" y2="6"/><line x1="8" y1="2" x2="8" y2="6"/><line x1="3" y1="10" x2="21" y2="10"/>
		</svg>
		{#if value}
			<span>{displayValue}</span>
		{:else}
			<span>set date</span>
		{/if}
	</button>

	<!-- Popover -->
	{#if open}
		<!-- svelte-ignore a11y_click_events_have_key_events -->
		<!-- svelte-ignore a11y_no_static_element_interactions -->
		<div class="fixed inset-0 z-[55] {isMobile ? 'bg-black/50 backdrop-blur-[2px]' : ''}" onclick={() => open = false}></div>

		<!-- svelte-ignore a11y_click_events_have_key_events -->
		<!-- svelte-ignore a11y_no_static_element_interactions -->
		<div
			class="{isMobile ? 'fixed inset-x-0 bottom-0 z-[60] w-full rounded-t-2xl animate-slideUp' : 'z-[60] w-64 rounded-xl animate-popIn'} bg-elevated border border-border shadow-xl overflow-hidden"
			style="{isMobile ? 'padding-bottom: env(safe-area-inset-bottom, 0px)' : popoverStyle}"
			onclick={(e) => e.stopPropagation()}
		>
			<!-- Quick shortcuts -->
			<div class="p-2 flex flex-wrap gap-1.5 border-b border-border">
				<button type="button" onclick={() => setDate(addDays(0))} class="px-2.5 py-1 rounded-lg text-xs bg-surface hover:bg-tertiary text-text-secondary hover:text-text transition-colors">today</button>
				<button type="button" onclick={() => setDate(addDays(1))} class="px-2.5 py-1 rounded-lg text-xs bg-surface hover:bg-tertiary text-text-secondary hover:text-text transition-colors">tomorrow</button>
				<button type="button" onclick={() => setDate(nextMonday())} class="px-2.5 py-1 rounded-lg text-xs bg-surface hover:bg-tertiary text-text-secondary hover:text-text transition-colors">monday</button>
				<button type="button" onclick={() => setDate(addDays(7))} class="px-2.5 py-1 rounded-lg text-xs bg-surface hover:bg-tertiary text-text-secondary hover:text-text transition-colors">next week</button>
				{#if value}
					<button type="button" onclick={() => setDate(null)} class="px-2.5 py-1 rounded-lg text-xs text-text-muted hover:text-danger transition-colors">clear</button>
				{/if}
			</div>

			<!-- Text input -->
			<div class="p-2 border-b border-border">
				<input
					bind:this={inputEl}
					bind:value={textInput}
					onkeydown={(e) => { if (e.key === 'Enter') { e.preventDefault(); handleTextSubmit(); } if (e.key === 'Escape') open = false; }}
					placeholder="fri, 3d, jun 15, 15h, 3pm..."
					class="w-full bg-surface border border-border rounded-lg px-2.5 py-1.5 text-xs text-text placeholder:text-text-muted/60 focus:outline-none focus:ring-2 focus:ring-text/8 focus:border-border-strong transition-all"
				/>
			</div>

			<!-- Time (only if date is set) -->
			{#if value}
				<div class="px-2 py-1.5 border-b border-border flex items-center gap-2">
					<svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" class="text-text-muted flex-shrink-0">
						<circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/>
					</svg>
					<div class="flex gap-1">
						{#each ['09:00', '12:00', '14:00', '17:00'] as t}
							<button
								type="button"
								onclick={() => { timeValue = t; applyTime(t); }}
								class="px-1.5 py-0.5 rounded text-[10px] transition-colors {timeValue === t ? 'bg-accent text-accent-fg' : 'bg-surface text-text-muted hover:text-text-secondary'}"
							>{t.replace(':00', 'h')}</button>
						{/each}
					</div>
					<input
						type="time"
						bind:value={timeValue}
						onchange={() => applyTime(timeValue)}
						class="bg-surface border border-border rounded px-1.5 py-0.5 text-[10px] text-text focus:outline-none w-[70px] ml-auto color-scheme-dark"
						style="color-scheme: {typeof document !== 'undefined' && document.documentElement.classList.contains('light') ? 'light' : 'dark'}"
					/>
					{#if timeValue}
						<button type="button" onclick={clearTime} class="text-[9px] text-text-muted hover:text-danger transition-colors">x</button>
					{/if}
				</div>
			{/if}

			<!-- Mini calendar -->
			<div class="p-2">
				<div class="flex items-center justify-between mb-2 px-1">
					<button type="button" onclick={prevMonth} class="w-5 h-5 flex items-center justify-center text-text-muted hover:text-text-secondary transition-colors rounded" aria-label="previous month">
						<svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><polyline points="15 18 9 12 15 6"/></svg>
					</button>
					<span class="text-[11px] text-text-secondary font-medium">{monthLabel}</span>
					<button type="button" onclick={nextMonth} class="w-5 h-5 flex items-center justify-center text-text-muted hover:text-text-secondary transition-colors rounded" aria-label="next month">
						<svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><polyline points="9 6 15 12 9 18"/></svg>
					</button>
				</div>
				<!-- Day headers -->
				<div class="grid grid-cols-7 gap-0 mb-1">
					{#each ['m', 't', 'w', 't', 'f', 's', 's'] as d}
						<div class="text-[9px] text-text-muted text-center py-0.5">{d}</div>
					{/each}
				</div>
				<!-- Days -->
				<div class="grid grid-cols-7 gap-0">
					{#each calendarDays as day}
						{#if day}
							<button
								type="button"
								onclick={() => selectDay(day)}
								class="w-full aspect-square flex items-center justify-center text-[11px] rounded-md transition-all {isSelected(day) ? 'bg-accent text-accent-fg font-medium' : isToday(day) ? 'text-text font-medium ring-1 ring-border-strong' : 'text-text-secondary hover:bg-surface hover:text-text'}"
							>{day}</button>
						{:else}
							<div></div>
						{/if}
					{/each}
				</div>
			</div>
		</div>
	{/if}
</div>

<style>
	.animate-popIn { animation: popIn 0.12s cubic-bezier(0, 0, 0.2, 1); }
	@keyframes popIn {
		from { opacity: 0; transform: translateY(-4px) scale(0.96); }
		to { opacity: 1; transform: translateY(0) scale(1); }
	}
	.animate-slideUp { animation: slideUp 0.2s cubic-bezier(0, 0, 0.2, 1); }
	@keyframes slideUp {
		from { transform: translateY(100%); }
		to { transform: translateY(0); }
	}
</style>
